version: '2'
services:
  backend:
    image: zenika/lunchplace_backend:develop-0.0.3
    labels:
      io.rancher.container.pull_image: always
    environment:
      SECURITY_USER_NAME: ${LP_RCT_SECURITY_USER_NAME}
      SECURITY_USER_PASSWORD: ${LP_RCT_SECURITY_USER_PASSWORD}
  frontend:
    image: zenika/lunchplace_frontend:develop-x
    labels:
      io.rancher.container.pull_image: always
    environment:
      API_URL: ${LP_RCT_API_URL}
      AUTH0_CLIENT_ID: ${LP_RCT_AUTH0_CLIENT_ID}
      AUTH0_CLIENT_DOMAIN: ${LP_RCT_AUTH0_CLIENT_DOMAIN}